### ISSUE TITLE
Automate deployment with startup script

### ISSUE THREAD

**Issue by benofben** [DSPN/oracle-bare-metal-cloud-dse#1]
Need to invoke install-datastax-redhat.  From discussion with Mahesh, it sounds like that will require a small script to be b64 encoded and pass in VM metadata.

**Comment by benofben** [comment]
Collin is working on doing this with LCM, but we can just use the existing install-datastax-redhat for now.

**Comment by gmflau** [comment]
The logic is now using Oracle BMC's metadata's user_data to pass in our scripts to kick off install-datastax-redhat scripts to install OpsCenter and DSE.
